CodeFx.Web/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CodeFx.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CodeFx.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookBusiness _bookBusiness;

        public BookController(IBookBusiness bookBusiness)
        {
            _bookBusiness = bookBusiness;
        }


        public IActionResult Index(string q)
        {
            var List = _bookBusiness.GetBooksSearch(q);
            return View(List);
        }
        //public PartialViewResult BookSearch(string q)
        //{
        //    var list = _bookBusiness.GetBooksSearch(q);
        //    return PartialView(list);
        //}

        public IActionResult Detail(int id)
        {
            if (id == 0) {
                return RedirectToAction("Index");
            }

            var book =  _bookBusiness.GetById(id);

            if (book == null) {
                return RedirectToAction("Index");
            }

            return View(book);
        }

        //public IActionResult Create()
        //{
            
        //    return View();
        //}
        //[HttpPost]
        //public IActionResult Create()
        //{

        //    return View();
        //}



    }
}

CodeFx.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CodeFx.Business.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CodeFx.Web.Controllers
{
    public class CategoryController : Controller
    {

        private readonly ICategoryBusiness _categoryBusiness;

        public CategoryController(ICategoryBusiness categoryBusiness)
        {
            _categoryBusiness = categoryBusiness;
        }
        // GET: Category
        public IActionResult Index()
        {
            var list=_categoryBusiness.GetCategories();
            return View(list);
        }

        // GET: Category/Details/5
        public IActionResult Details(int id)
        {
            var cat = _categoryBusiness.CategoriesWithBooks(id);
            return View(cat);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Category/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Category/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CodeFx.Web/Views/Category/Details.cshtml
@using CodeFx.ViewModel.Book
@model IEnumerable<CodeFx.ViewModel.Category.CategoriesWithBooks>


<h2>Bu kategorideki kitaplar</h2>


<table class="table">
    <thead>
        <tr>
            <th>
                Kategori nosu
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            @foreach (BookforCtgItem book in item.Books)
            {
            <td>
                <div class="owl-item">
                    <div class="col-sm-4">
                        <div class="ex-product">
                            <a href="#"><img src="~/images/ggw.jpg" alt="category picture" /></a>
                            <h4 class="shop-item-title font-alt"><a asp-controller="Book" asp-action="Detail/@book.Id">@book.Name</a></h4>
                        </div>
                    </div>
                </div>
            </td>
            }
            
        </tr>
}
    </tbody>
</table>
<h4><a asp-controller="Category" asp-action="Index">Kategori anasayfası</a></h4>

CodeFx.Web/Views/Category/Index.cshtml
@model IEnumerable<CodeFx.ViewModel.Category.CategoryItem>



<section class="module">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <h3 class="module-title font-alt">Kategoriler</h3>
                    
                </div>
            </div>
            <div class="row">
                <div class="owl-carousel text-center" data-items="5" data-pagination="true" data-navigation="false">
                    @foreach (var item in Model)
                    {
                    <div class="owl-item">
                        <div class="col-sm-4">
                            <div class="ex-product">
                                <a href="#"><img src="~/images/ggw.jpg" alt="category picture" /></a>
                                <h4 class="shop-item-title font-alt"><a href="/Category/Details/@item.Id"> @Html.DisplayFor(modelItem => item.Name)</a></h4>
                            </div>
                        </div>
                    </div>
                    }                  
                    
                </div>
            </div>
        </div>
    </section>